### ISSUE TITLE
cant start in game bot in my ssl host 

### ISSUE THREAD

**Issue by aliayoubi** [ernestoyaquello/KeepieUppie#1]
hi 
how can i start geme in ssl host

**Comment by ernestoyaquello** [comment]
Sorry, but this repository is just to show the bot I created, and that's why there are no instructions about how to set it up. In case you are interested in how the code could be used, all that you would have to do is to follow the instructions of the [Telegram API](https://core.telegram.org/bots/api#setwebhook) in order to create and configure your bot. Then, in the web server in which you would have uploaded all the files, you would have to update the file `bot_config.php` with your values. And that's about it.

Regarding the SSL issue, I can assure you that this code works using HTTPS because I was using it in my web server when it was still up and running, and the bot worked perfectly. In fact, the Telegram API requires your webhook to use HTTPS, so SSL is definitely not a problem for this code to run.

My apologies for the immense delay in the answer, I completely forgot about this.
